exchange-rates:
    path: /api/exchange-rates
    controller: App\Controller\Api\ExchangeRatesController::index

index:
    path: /{wildcard}
    defaults: {
        _controller: App\Controller\DefaultController::index
    }
    requirements:
        wildcard: .*
    # controller: App\Controller\DefaultController::index

