api_exchange-rates:
    path: /api/exchange-rates
    controller: App\ExchangeRate\Controller\Api\ExchangeRatesController::index
    methods: GET

web_index:
    path: /{wildcard}
    defaults: {
        _controller: App\Web\Controller\DefaultController::index
    }
    requirements:
        wildcard: .*

