api_exchange-rates:
    path: /api/exchange-rates
    controller: App\ExchangeRate\Controller\Api\ExchangeRatesController::index
    methods: GET

api_setupcheck:
    path: /api/setup-check
    controller: App\Web\Controller\DefaultController::setupCheck

web_index:
    path: /{wildcard}
    defaults: {
        _controller: App\Web\Controller\DefaultController::index
    }
    requirements:
        wildcard: .*

